export const famousQuotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "In this life we cannot do great things. We can only do small things with great love. - Mother Teresa",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. - Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Only the paranoid survive. - Andy Grove",
    "It's hard to beat a person who never gives up. - Babe Ruth",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "What we think, we become. - Buddha",
    "All our dreams can come true, if we have the courage to pursue them. - Walt Disney",
    "The best revenge is massive success. - Frank Sinatra",
    "If you're going through hell, keep going. - Winston Churchill",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "Winning isn't everything, but wanting to win is. - Vince Lombardi",
    "Every child is an artist. The problem is how to remain an artist once he grows up. - Pablo Picasso",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "The best way to predict the future is to invent it. - Alan Kay",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Go confidently in the direction of your dreams and live the life you have imagined. - Henry David Thoreau",
    "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. - Helen Keller",
    "Life is 10% what happens to me and 90% of how I react to it. - Charles Swindoll",
    "An unexamined life is not worth living. - Socrates",
    "Eighty percent of success is showing up. - Woody Allen",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "The only way to have a friend is to be one. - Ralph Waldo Emerson",
    "Life is what happens to you while you're busy making other plans. - John Lennon",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas Edison",
    "The mind is everything. What you think you become. - Buddha",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "It is never too late to be what you might have been. - George Eliot",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "In order to write about life first you must live it. - Ernest Hemingway",
    "The big lesson in life, baby, is never be scared of anyone or anything. - Frank Sinatra",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. - Leo Burnett",
    "Life is not a problem to be solved, but a reality to be experienced. - Soren Kierkegaard",
    "The good life is one inspired by love and guided by knowledge. - Bertrand Russell",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "May you live every day of your life. - Jonathan Swift",
    "Life itself is the most wonderful fairy tale. - Hans Christian Andersen",
    "Do not let making a living prevent you from making a life. - John Wooden",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
    "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine. - Neil Armstrong",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Not how long, but how well you have lived is the main thing. - Seneca",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Money and success don't change people; they merely amplify what is already there. - Will Smith",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Don't count the days, make the days count. - Muhammad Ali",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "You have to be burning with an idea, or a problem, or a wrong that you want to right. If you're not passionate enough from the start, you'll never stick it out. - Steve Jobs",
    "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed. - Michael Jordan",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere. - Barack Obama",
    "It is better to fail in originality than to succeed in imitation. - Herman Melville",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis"
];

export function getRandomQuote(): string {
    return famousQuotes[Math.floor(Math.random() * famousQuotes.length)];
}
